@ECHO OFF
"C:\ASM\AVR\AvrAssembler2\avrasm2.exe" -S "C:\ASM\AVR\PROJECTS\IPK-48\labels.tmp" -fI -W+ie -o "C:\ASM\AVR\PROJECTS\IPK-48\IPK_48.hex" -d "C:\ASM\AVR\PROJECTS\IPK-48\IPK_48.obj" -e "C:\ASM\AVR\PROJECTS\IPK-48\IPK_48.eep" -m "C:\ASM\AVR\PROJECTS\IPK-48\IPK_48.map" "C:\ASM\AVR\PROJECTS\IPK-48\IPK_48.asm"
